### ISSUE TITLE
Your comments, suggestions and problems that you have encountered

### ISSUE THREAD

**Issue by aakechin** [aakechin/cutPrimers#1]
Dear users of **cutPrimers**! We will be glad to hear from you any comments (positive or negative) about using **cutPrimers**. If you have any problems, please let us know. We will try to answer you as soon as it is possible. But I think we will be able to answer during **24 hours**. Thank you for using **cutPrimers** that **removes primer sequences from NGS reads**!

**Comment by iadamo1** [comment]
Hi, I would like to install cutPrimers on my ubuntu and I have followed the instructions provided here. 
1. sudo apt-get install python3-biopython
2. sudo apt-get install python3-regex
3. sudo apt-get install python3-argparse, here I get an error: E: Unable to locate package python3-argparse
4. python3 cutPrimers.py : python3: can't open file 'cutPrimers.py': [Errno 2] No such file or directory
So I tried the instruction on the https://pypi.python.org/pypi/argparse but still nothing. plus in my urs/local/bin I have both python 2.7 and 3.5 so when I tried to install the package manually it said that in was already in my python 2.7. 
it may be something basic but I could not solve it. thanks a lot for any help
Irene

**Comment by aakechin** [comment]
@iadamo1, thank you for your comment! There is a mistake in the installation manual (I've corrected it). There is actually no package with name 'python3-argparse' in the apt-get. You should install it with the following command:
"sudo pip3 install argparse".
Also you have another variant. If you have already downloaded argparse. You can install it with command "python3 setup.py install". Actually, if you want to use some python package with python v2 and python v3, you should install it twice, with "python2 setup.py install" and "python2 setup.py install". I hope, this will help. If in this case, you will still have any problems, write to me.

**Comment by iadamo1** [comment]
Thanks a lot for your help! I installed the package argparse but when I use the command:
python3 cutPrimers.py -h I still get this error
python3: can't open file 'cutPrimers.py': [Errno 2] No such file or directory
thanks again for your availability!

**Comment by aakechin** [comment]
Before the command “python3 cutPrimers.py” you should go to the folder with cutPrimers.py. To do it, use command “cd cutPrimers-master” (or another folder name, in which cutPrimers.py is located). Hope this will help

**Comment by gonzalezem** [comment]
Hi! Are all IUPAC nucleotide codes (wildcard characters like N, W...) supported?

**Comment by aakechin** [comment]
Hello, @gonzalezem! Only standard characters can be used in cutPrimers. However, you can use argument "--error-number" that make it insensitive to some number of "mutations" in primers. So, any wildcard will be considered by cutPrimers as an "error".
Also,  I added script makeSequencesFromSeqWithAmbiguousLetters.py that converts sequences with any number of wildcards to all possible sequences with common characters (A, T, G, C). This way is much slower. You can try it, hope it will help.

**Comment by joblingm** [comment]
never used python before - trying to get cutprimers under windows 7 working to trim my illumina paired read files - 
got python installed; added to path; biopython regex and argeparse installed. Then at least two issues come up 1)  tried putting cutprimers.py in python folder (path was added during install) but seems it needs to be in my working directory 2) example tells me to use python3 to run cutprimers but in windows that is a dll not exe, and fails - using python works BUT then cutprimers says warning you do not have pysam installed and quits - seems like its just a warning but cutprimers doesnt do anything after that. thought about installing pysam but get a warning about no cython etc.  No output files created. What am I doing wrong? any help appreciated.

edit1 looking at code it checks for pysam line 14,15 and gives warning if not there, but then on line 20 it tries to import pysam anyway? can I just edit and delete that import?
edit2 I removed pysam from line 20 and it got past there but then failed on line 252 with minprimer3len is not defined' now I'm getting way past where I want to be - minprimer3len is defined in line59 = to minprimer3len2 defined on line36 but i dont seen any value set - of course i have no idea if thats needed or where that might be... Botto line is its not working for me!
edit3 update screen capture of cmd window errors
![cutprimerscmd2](https://user-images.githubusercontent.com/48600587/54458607-0172a580-472a-11e9-9335-ae77cad19611.jpg)

FYI this may all be moot - what I am trying to do is remove primer remnants from r1 and r2 fastq files that the core facility gave me with indexes already removed; its just that these files many reads have residual primer sequences left on and that is what I want to remove (their library prep did not size correctly and so many inserts were under 250 bp so 2 x 250 reads on miseq run into primers on the other end which they didnt account for) - so many reads start with variable lengths of the 3' ends of the primers e.g. here's the 3' end of a fwd read with primer still attached (shown after -)
genomic AAACGATCTATTCACCTGAA-AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTC
G untrimmed primer read, and the 5' end of its paired mate - 
untrimmed primer seq TCCACTCGTGACTAGAGTTCAGACGTGTGCTCTTCCGATCT-TAATTAATCCCTCAGAAAT  genomic.

Is cutprimer the right tool to do this? Many reads are fine 250 bp of genomic DNA!

**Comment by aakechin** [comment]
@joblingm, thank you very much for your so detailed comment! There were really some bugs that were not fixed for Windows users. I removed repeated command of importing pysam and made variable minprimer3len to be global. I replaced cutPrimers with new version of file, now you can download it. I tried it in Windows 7 and it worked.

About your goals of using cutPrimers. Are these primer sequences the same for all reads, one for R1-reads and the second one for R2-reads? Or there are many different primers for R1-reads and many for R2-reads? If the 1st variant, I'd recommend to use tools for trimming adapters, like Trimmomatic, they are faster. If the 2nd variant, cutPrimers is what you need. If you have more questions, do not hesitate to ask them again. I'll try to answer as quick as possible.

**Comment by joblingm** [comment]
Many thanks for the quick reply – and suggestions. The primers R1 and R2 are the same for all reads; I was looking for a program that would removes these remnants without me having to run virtual machines or OS’s and thats why I hadnt considered using trimmo – but I found that the galaxy web site/servers run trimmo in their GUI and it looks like it does the job nicely for me!

**Comment by shigej38** [comment]
First of all, thank you for developing the cutPrimer program. my problem with the cutPrimer my hand only the MEFV gene belonging to the fastq.gz pair-end data can cut the primers easily, but within a single fastq.gz pair-end data if more than one of the sequence data is contained in the sequence does not do the primer data cut. I can't introduce my primer data to the cutPrimer program.

**Comment by aakechin** [comment]
@shigej38, thank you for your comment. Unfornunately, I couldn't understand your problem. You have paired-end data, right? Each of the file contains many NGS-reads of several genes, including MEFV, yes? And primers can be trimmed by cutPrimers only from reads of MEFV? Please, could you give me more description with your task and/or problem?

**Comment by shigej38** [comment]
@aakechin  There are R1 and R2 readings that contain the mefv gene, and another raw data that contains double-ended raw data and ten gene regions (these data are in separate fastq files.) CutPrimers can only break data from the mefv gene, but not the ten genes. The fastq data of 200 mb, each of which is 200 mb, is output t1 and -t2, and 100 bytes -utr1 and -utr2 data is 300 mb.

**Comment by aakechin** [comment]
@shigej38 could you please send me part of your files with primers and reads? I will see what is the problem. You can send it to my personal e-mail: a.a.kechin gmail com

**Comment by shigej38** [comment]
@aakechin I have sent the necessary data Do you check your mail?

**Comment by Lrjzon** [comment]
Hi,
We have single end reads with forward and reverse primers at the ends of each read. We are trying to trim these primer sequences with the tool CutPrimer. When trying to use both of the primer files (-pr15 and -pr13) we receive an error message from CutPrimer: UnboundLocalError: local variable 'primerNum2' referenced before assignment. Any idea on how we can correctly cut both primer sequences from the reads?

**Comment by aakechin** [comment]
> Hi,
> We have single end reads with forward and reverse primers at the ends of each read. We are trying to trim these primer sequences with the tool CutPrimer. When trying to use both of the primer files (-pr15 and -pr13) we receive an error message from CutPrimer: UnboundLocalError: local variable 'primerNum2' referenced before assignment. Any idea on how we can correctly cut both primer sequences from the reads?

@Lrjzon, thank you for your comment! There was really a bug with this variable. Try it again now, it should work. If there are some new problems, do not hesitate to report about it.

**Comment by Lrjzon** [comment]
@aakechin Thanks for your reply! The error has been resolved, but I'm a little bit confused about my trimmed and untrimmed output files. I end up with a file trimmed file that is 19 kb and an untrimmed file that is 224,520 kb. Does this mean that almost all files were unable to be trimmed, or does it mean that the trimmed file only contains the removed primer sequences? I ran cutPrimer with default settings

**Comment by Lrjzon** [comment]
Looks like I had a incorrect primer file. From looking at other posts from you, it appears to me that I should have a primer file with reverse primers and a primer file with the reverse complemented forward primers. After adjusting my primer files I now have a trimmed file with 31,214 kb and an untrimmed file with 203,197 kb. Still a lot of reads that were not able to be trimmed. When I increase the error-number parameter to 8 I get less trimmed reads while I expected there to be more trimmed reads because of the more leniant error number. Your thoughts?

**Comment by aakechin** [comment]
@Lrjzon sorry, I've missed your answers. In such cases I try to study the untrimmed reads manually, namely I take some reads and try to find primer sequences in them. Such manual analysis commonly gives the answer why so many untrimmed reads are obtained.
Considering strange results for changing error-number parameter, I think I need to perform some tests to identify the reason of it.
